using System.Collections.Generic;
using System.Text.RegularExpressions;
using NUnit.Framework;
using TypingApp.Models;
using List = System.Windows.Documents.List;

namespace Tests;

public class AutoGeneratedExercisesTests
{
    private static Regex _validator { set; get; }

    [SetUp]
    public void Setup()
    {
    }

    /*
     * ====================
     * ExerciseModel tests
     * ====================
     */
    [Test]
    public void Should_ReturnExerciseWithE_When_CharactersHasOnlyE()
    {
        var characters = new List<Character> { new('e') };
        
        var exercise = new Exercise(characters);
        
        _validator = new Regex(@"^[e ]+$");
        Assert.True(_validator.IsMatch(exercise.Text));
    }

    [Test]
    public void Should_ReturnCorrectExercise()
    {
        var characters = new List<Character>
        {
            new('e'),
            new('a'),
            new('n'),
            new('t'),
        };
        
        var exercise = new Exercise(characters);
        
        _validator = new Regex(@"^[eant ]+$");
        Assert.True(_validator.IsMatch(exercise.Text));
    }
}