using System.Collections.Generic;
using System.Text.RegularExpressions;
using NUnit.Framework;
using TypingApp.Models;

namespace Tests.UnitTests;

[TestFixture]
public class AutoGeneratedExercisesTests
{
    private static Regex _validator { set; get; }

    [SetUp]
    public void Setup()
    {
    }
    
    [Test]
    public void Exercise_Ctor_Should_ReturnCorrectExerciseWithEANT_When_CharactersAreEANT()
    {
        // Arrange
        _validator = new Regex(@"^[eant ]+$");
        var characters = new List<Character>
        {
            new('e'),
            new('a'),
            new('n'),
            new('t'),
        };
        
        // Act
        var exercise = new Exercise(characters);
        
        // Assert
        Assert.True(_validator.IsMatch(exercise.Text));
    }
}